### PR TITLE
fix: correctly update style when calling Graph methods

### LINKED ISSUE #326: Graph.setCellStyles may not propagate style changes
Seen in #325
When calling Graph.setCellStyles to change the fillColor, the fill color doesn't change in the browser.

### PR DESCRIPTION
**Pull request by tbouffard**
`GraphDataModel.setStyle` does the actual style change. Its current implementation requires to pass an instance of CellStyle which is different from the current style hold by the Cell. Previously, the Graph methods directly update the Cell style instance prior calling the style update so nothing happened.
The problem was spotted in the Monitor story which is now fixed.
Also fix the signature of Graph.setCellStyle as the `cells` parameter is optional (previously, it was marked as mandatory).

Introduce a convenient `Cell.getClonedStyle` method to ease style update and update the JSDOC of several functions to warn users about how to correctly make the style update happen.

The fix has a slight side effects exhibited by the EdgeMixin tests. The `sourcePort` and `targetPort` cell style properties are now set to null at vertex insertion. This should not have any effects for the end user.

### Notes

Closes #326

### Monitor story

This PR fix the problem described in #325.

**_mxGraph_**
mxGraph

**_maxGraph PR 325_**
maxGraph_PR_325

**_now with this PR_**

https://github.com/maxGraph/maxGraph/assets/27200110/023ef670-5088-418b-a40b-59de880fe467

### CODE REVIEW

File: packages/core/src/view/mixins/CellsMixin.ts [hunk 1]
```diff
@@ -70,6 +70,16 @@ declare module '../Graph' {
...
+     * Sets the style of the specified cells. If no cells are given, then the selection cells are changed.
+     *
+     * **IMPORTANT**: Do not pass {@link Cell.getStyle} as value of the `style` parameter. Always get a clone of the style of the cell with {@link Cell.getClonedStyle}, then update it and pass the updated style to this method.
+     * For more details, see {@link GraphDataModel.setStyle}.
+     *
+     * @param style String representing the new style of the cells.
+     * @param cells Optional array of {@link Cell} to set the style for. Default is the
+     * selection cells.
+     */
     setCellStyle: (style: CellStyle, cells: Cell[]) => void;
```
Comment (tbouffard) [inline packages/core/src/view/mixins/CellsMixin.ts]:
```suggestion
    setCellStyle: (style: CellStyle, cells?: Cell[]) => void;
```
