### PR TITLE
fix: correct rotation handle positioning during vertex rotation

### LINKED ISSUE #482: [BUG] In Handles and Stencils stories, the rotation handle is always located on the right of the vertex
### Describe the bug
**Note: this is visible in Stories but the problem probably occurs in all applications.**

The "rotation handle" is always located on the right of the vertex, even after having done some rotation.
So, on a next rotation, the initial orientation of the preview does not match the current orientation of the vertex. 

### To Reproduce

For the `Handles` story, see https://maxgraph.github.io/maxGraph/demo/?path=/story/layouts-handles--default or run the story locally.
Same for the `Stencils` story.

### Expected behavior

In mxGraph examples

### Handles

https://jgraph.github.io/mxgraph/javascript/examples/handles.html

https://github.com/maxGraph/maxGraph/assets/27200110/e0f53aa3-6d85-415a-b2d3-34d4c908bd0a

### Stencils

https://jgraph.github.io/mxgraph/javascript/examples/stencils.html

https://github.com/maxGraph/maxGraph/assets/27200110/a89683d9-2e9a-422c-b6eb-7a7cb3466249

### Handles

https://github.com/maxGraph/maxGraph/assets/27200110/be63c6ce-0761-4487-8226-2b161807b33e

### Stencils

https://github.com/maxGraph/maxGraph/assets/27200110/95c79b3d-3608-4d23-9cc6-50699a93af17

### Environment
- Desktop
- OS and version: Ubuntu 20.04
- Browser and version: Firefox 126.0.1, Chrome 126.0.6478.126
- commit 50eb99b with the commit of #480

### LINKED ISSUE #590: [BUG] `VertexHandler.currentAlpha` is not calculated correctly
### Describe the bug
This problem was detected during the review of #581. More details about the investigation are available in the PR.

In `mxGraph`, `currentAlpha` was null at `VertexHandler` instance construction, in maxGraph, its value is 100.
My guess is that the value 100 was probably chosen because the property name including the “alpha” term was mistakenly considered to carry information about opacity. This property name is used for this purpose in several places in the code, such as AbstractCanvas2D.

In #581, while trying to fix the angle of the rotation handle in the `redrawHandles` method:
Before the fix https://github.com/maxGraph/maxGraph/blob/v0.14.0/packages/core/src/view/handler/VertexHandler.ts#L1886
```ts
const alpha = toRadians(this.currentAlpha);
```

mxGraph code https://github.com/jgraph/mxgraph/blob/v4.2.2/javascript/src/js/handler/mxVertexHandler.js#L2019
```js
var alpha = mxUtils.toRadians((this.currentAlpha != null) ? this.currentAlpha : this.state.style[mxConstants.STYLE_ROTATION] || '0');
```

Trying to use the ported mxGraph statement didn't work: the currentAlpha is always defined, so its value would have been used. As it is incorrectly computed, a wrong value would have been set to the angle. 
```ts
const alpha = toRadians(this.currentAlpha ?? (this.state.style.rotation ?? 0));
```

### To Reproduce
1. Update the code of `VertexHandler` to use currentAlpha to set the alpha 
2. Play with a story where the rotation of vertex is enabled, for example the **Stencils** or **Handles** stories 
3. Rotate a vertex, stop. Then rotate it again
4. Both the rotation handle and the preview shape are not at the right position

### Expected behavior
We should be able to restore the mxGraph code and make the rotation work correctly in this case as well.

### Screenshots
N/A

### Environment
All, the problem is in the algorightm and applies all the time.

### PR DESCRIPTION
**Pull request by HalilFocic**
## PR Checklist

- [x] Addresses an existing open issue: fixes #590  and #482  
- [x] You have discussed this issue with the maintainers of `maxGraph`, and you are assigned to the issue.
- [x] The scope of the PR is sufficiently narrow to be examined in a single session. A PR covering several issues must be split into separate PRs. Do not create a large PR, otherwise it cannot be reviewed and you will be asked to split it later or the PR will be closed.
- [x] I have added tests to prove my fix is effective or my feature works. This can be done in the form of automatic tests in `packages/core/_tests_` or a new or altered Storybook story in `packages/html/stories` (an existing story may also demonstrate the change).
- [x] I have provided screenshot/videos to demonstrate the change. If no releavant, explain why.
- [x] ~~I have added or edited necessary documentation,~~ or no docs changes are needed.
- [x] The PR title follows the ["Conventional Commits"](https://www.conventionalcommits.org/en/v1.0.0/) guidelines.

## Overview
After initial PR and suggestion to try to get the behaviour like mxGraph did I figured out the problem. Issue was:
- Incorrect value of currentAlpha on initialization ( was 100 instead of null)
- No call to set currentAlpha to null inside reset function
- Using currentAlpha directly inside redrawHandles function without checking if it is not null.

## Notes
I will close previous PR since this code better resembles mxGraph initial functionality.
Videos were not provided since functionality is the same as previous PR, not point in recording again. If needed, I can provide videos.

Closes #482 
Closes #590

### Screenshots

Both stencils and handles stories now properly work while rotating:

https://github.com/user-attachments/assets/3349db44-1453-4090-a43e-cc56a8de970f

https://github.com/user-attachments/assets/e901e45f-e74d-41e0-8dbb-df49b6fb7cbc

## Summary by CodeRabbit

- **New Features**
	- Enhanced management of the `currentAlpha` property, allowing it to represent an uninitialized state.

- **Bug Fixes**
	- Improved handling of `currentAlpha` to ensure calculations accommodate potential null values, enhancing robustness.

### CODE REVIEW

File: packages/core/src/view/handler/VertexHandler.ts [hunk 1]
```diff
@@ -1883,7 +1884,9 @@ class VertexHandler {
     }
 
     if (this.rotationShape) {
-      const alpha = toRadians(this.currentAlpha);
+      const alpha = toRadians(
+        this.currentAlpha !== null ? this.currentAlpha : this.state.style.rotation || 0
+      );
```
Comment (tbouffard) [inline packages/core/src/view/handler/VertexHandler.ts]: **suggestion:** We could use the _nullish_ coalescing operator (??) to provide a more concise and readable way to handle null and undefined values as suggested in #590
```ts
const alpha = toRadians(this.currentAlpha ?? (this.state.style.rotation ?? 0));
```

File: packages/core/src/view/handler/VertexHandler.ts [hunk 2]
```diff
@@ -1353,6 +1353,7 @@ class VertexHandler {
     }
 
     this.index = null;
+    this.currentAlpha = null;
```
Comment (tbouffard) [inline packages/core/src/view/handler/VertexHandler.ts:1356]: **praise:** Nice, mimic https://github.com/jgraph/mxgraph/blob/v4.2.2/javascript/src/js/handler/mxVertexHandler.js#L1445

**Review by tbouffard — APPROVED** [review]
LGTM, good job !
