### PR TITLE
fix(connectionHandler): apply perimeter style to new edges

### LINKED ISSUE #840: FixedPoints Story: the edge are connected on a rectangle perimeter instead on the connection constraints of the vertex
### Describe the bug

Here is what I see with maxGraph:

https://github.com/user-attachments/assets/f4ff0e84-73bd-40b9-b9e3-c4a34666b3bf

### Expected behavior
The connection points should be on the perimeter of the vertex, as this was done in mxGraph

https://github.com/user-attachments/assets/f2ffb227-1e68-4a44-8c31-cdae495ef220

mxGraph resources:
- source: https://github.com/jgraph/mxgraph/blob/v4.2.2/javascript/examples/fixedpoints.html
- live example: https://jgraph.github.io/mxgraph/javascript/examples/fixedpoints.html

### Environment
- `maxGraph` version or commit: #839
- Desktop or mobile: desktop
- OS and version:  ubuntu 24.04
- Browser and version:  Firefox 138.0.4, Chrome 136.0.7103.113

### PR DESCRIPTION
**Pull request by LOUISNOYEZ**
## PR Checklist

- [x] Addresses an existing open issue: closes #840. 
- [x] You have discussed this issue with the maintainers of `maxGraph`, and you are assigned to the issue.
- [x] The scope of the PR is sufficiently narrow to be examined in a single session. A PR covering several issues must be split into separate PRs. Do not create a large PR, otherwise it cannot be reviewed and you will be asked to split it later or the PR will be closed.
- [x] I have added tests to prove my fix is effective or my feature works. This can be done in the form of automatic tests in `packages/core/_tests_` or a new or altered Storybook story in `packages/html/stories` (an existing story may also demonstrate the change).
- [x] I have provided screenshot/videos to demonstrate the change. If no releavant, explain why.
- [x] I have added or edited necessary documentation, or no docs changes are needed.
- [x] The PR title follows the ["Conventional Commits"](https://www.conventionalcommits.org/en/v1.0.0/) guidelines.

## Overview

Restore mxgraph new edges endpoints positionning when using the connection handler to connect vertex cell shapes with non rectangular perimeters.

### Bug description

When using the connection handler to connect cell shapes which have a non rectangular perimeter, the new edge preview displays correctly, but when the new edge is created, its endpoints are connected to connection points on the rectangular bounding box of the cell shape instead of to the connection points projected on the perimeter of cell shapes.
This pull request is intended to fix issue #840 although this bug occurs on any graph which uses the connection handler and vertex with non rectangular perimeters.

Demonstration using the [Fixed Points story](https://github.com/maxGraph/maxGraph/blob/24357a7eb79a67b91a0d1c815a8e45c615188499/packages/html/stories/FixedPoints.stories.ts)

- Current maxgraph behavior : The new edge connects to the bounding box of the cell shape instead of connecting to the actual perimeter of the cell shape.

  https://github.com/user-attachments/assets/3f82f04c-64e4-4dc4-831b-00586342fe4b

- Intended mxgraph behavior : the new edge connects directly to the perimeter of the cell shape.

  https://github.com/user-attachments/assets/be6e79e9-eee4-4dd4-b8be-c2f376a2cc9e

### Analysis

As per the [migration guide](https://github.com/maxGraph/maxGraph/blob/24357a7eb79a67b91a0d1c815a8e45c615188499/packages/website/docs/usage/migrate-from-mxgraph.md) from mxgraph to maxgraph, some styling properties that used to be set using strings `"0"` or `"1"'` have been replaced with `boolean` values.

https://github.com/maxGraph/maxGraph/blob/24357a7eb79a67b91a0d1c815a8e45c615188499/packages/website/docs/usage/migrate-from-mxgraph.md?plain=1#L533

This includes the properties `entryPerimeter` and `exitPerimeter` of edge's style, which dictate whether edges should take the perimeter into account when connecting.

https://github.com/maxGraph/maxGraph/blob/24357a7eb79a67b91a0d1c815a8e45c615188499/packages/website/docs/usage/migrate-from-mxgraph.md?plain=1#L545-L546

This type change has been taken into account accross the codebase, but not everywhere. Specifically it has not been taken into account for the connection handler in its [connection handler mixin](https://github.com/maxGraph/maxGraph/blob/24357a7eb79a67b91a0d1c815a8e45c615188499/packages/core/src/view/mixin/ConnectionsMixin.ts).

When creating new edges via connections, this style property is still set using a `string` in the `setConnectionConstraint` method, and they are thus ignored :

https://github.com/maxGraph/maxGraph/blob/24357a7eb79a67b91a0d1c815a8e45c615188499/packages/core/src/view/mixin/ConnectionsMixin.ts#L203-L207

This issue is fixed by setting the appropriate values :

```typescript
    if (!constraint.perimeter) {
      this.setCellStyles(source ? 'exitPerimeter' : 'entryPerimeter', false, [edge]);
    } else {
      this.setCellStyles(source ? 'exitPerimeter' : 'entryPerimeter', true, [edge]);
    }
```

## Notes

- I've added no tests under packages/core/\_\_tests\_\_. Correctness can be assed using any story involving the connection handler and cell shapes with non rectangle perimeters.
- The `setCellStyles` method does not take advantage of the typescript type checker to catch these kinds of mistakes statically. Its signature is
    ```typescript
    setCellStyles: (key: keyof CellStateStyle, value: CellStateStyle[keyof CellStateStyle], cells?: Cell[]) => void
    ```  
  However there is no direct correlation between the first argument `key` and the type of the second argument `value`. Its type is a union of all types of `CellStateStyle` properties, which includes `string`, hence why typescript doesn't catch the error. I believe a possible solution might be to pass an object to setCellStyles to update styles instead of two separate arguments in order to catch errors, maybe
  ```typescript
  setCellStyles: (style: Partial<CellStateStyle>, cells?: Cell[]) => void
  ```
  This change is probably far reaching and would probably involve a large refactor.
- It's probably not a good idea for to use ternary operators in arguments to resolve keys at runtime, which might confuse the typescript type checker.

## Keywords

closes #840 

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved handling of connection perimeter constraints so connection styling is applied consistently, leading to more predictable and reliable connection behavior.

### CODE REVIEW

File: packages/core/src/view/mixin/ConnectionsMixin.ts [hunk 1]
```diff
@@ -201,9 +201,9 @@ export const ConnectionsMixin: PartialType = {
 
           // Only writes 0 since 1 is default
           if (!constraint.perimeter) {
-            this.setCellStyles(source ? 'exitPerimeter' : 'entryPerimeter', '0', [edge]);
+            this.setCellStyles(source ? 'exitPerimeter' : 'entryPerimeter', false, [edge]);
           } else {
-            this.setCellStyles(source ? 'exitPerimeter' : 'entryPerimeter', null, [edge]);
+            this.setCellStyles(source ? 'exitPerimeter' : 'entryPerimeter', true, [edge]);
```
Comment (tbouffard) [inline packages/core/src/view/mixin/ConnectionsMixin.ts:207]: **suggestion:** here we can keep null, the default value will be then used (true). This is what the comment line 202 tries to explain (I guess).

File: packages/core/src/view/mixin/ConnectionsMixin.ts [hunk 2]
```diff
@@ -201,9 +201,9 @@ export const ConnectionsMixin: PartialType = {
 
           // Only writes 0 since 1 is default
```
Comment (tbouffard) [inline packages/core/src/view/mixin/ConnectionsMixin.ts]: **nitpick:** 
```suggestion
          // Only writes false since true is default
```

File: packages/core/src/view/mixin/ConnectionsMixin.ts [hunk 3]
```diff
@@ -201,9 +201,9 @@ export const ConnectionsMixin: PartialType = {
...
           if (!constraint.perimeter) {
-            this.setCellStyles(source ? 'exitPerimeter' : 'entryPerimeter', '0', [edge]);
+            this.setCellStyles(source ? 'exitPerimeter' : 'entryPerimeter', false, [edge]);
```
Comment (tbouffard) [inline packages/core/src/view/mixin/ConnectionsMixin.ts]: **nitpick:** fix lint error 😄

**Review by tbouffard — COMMENTED** [review]
Thanks for your contribution.

There are some minor errors to fix.
I need to manually test storybook with this PR, but it looks fine.

Regarding the possible improvements in the signature of setCellStyles, I have proposed #1028 that is able to catch errors like the one fixed here

File: packages/core/src/view/mixin/ConnectionsMixin.ts (hunk 1 above)
Comment (LOUISNOYEZ) [reply packages/core/src/view/mixin/ConnectionsMixin.ts:207]: From my tests in the Fixed Points story, the new edge fails to connect to the perimeter of the shape when the value is set to `null`. I've tried to search through the files but I couldn't find code indicating that the style value would default to `true` when the value `null` is used. The properties `entryPerimeter` and `exitPerimeter` do not appear to be set to a default value in the default stylesheet.
Incidentally, entryPerimeter/exitPerimeter is also set to null on line 195. I'm not sure if the intent is to set it to default, but I cannot find any default. I assume maxgraph treats it as "false" in this case.

File: packages/core/src/view/mixin/ConnectionsMixin.ts (hunk 2 above)
Comment (LOUISNOYEZ) [reply packages/core/src/view/mixin/ConnectionsMixin.ts]: I cannot find any indication that true is default for the entryPerimeter/exitPerimeter style property. I believe the property should probably be set explicitely, and this comment might be removed.

File: packages/core/src/view/mixin/ConnectionsMixin.ts (hunk 3 above)
Comment (LOUISNOYEZ) [reply packages/core/src/view/mixin/ConnectionsMixin.ts]: Lint error fixed !

File: packages/core/src/view/mixin/ConnectionsMixin.ts (hunk 1 above)
Comment (tbouffard) [reply packages/core/src/view/mixin/ConnectionsMixin.ts:207]: OK, fine, let's set it to true, this is also more explicit.

The default value for `exitPerimeter` is documented in https://github.com/maxGraph/maxGraph/blob/24357a7eb79a67b91a0d1c815a8e45c615188499/packages/core/src/types.ts#L275-L280 and it is supposed to be `true` (the same applies to `entryPerimeter`).

In mxGraph, the default was actually  `true`.

https://github.com/jgraph/mxgraph/blob/ff141aab158417bd866e2dfebd06c61d40773cd2/javascript/src/js/view/mxGraph.js#L6787-L6793
```js
perimeter = mxUtils.getValue(edge.style, (source) ? mxConstants.STYLE_EXIT_PERIMETER :
			mxConstants.STYLE_ENTRY_PERIMETER, true);
```


But what I see in the maxGraph code is that the default is `false` 😭 
https://github.com/maxGraph/maxGraph/blob/24357a7eb79a67b91a0d1c815a8e45c615188499/packages/core/src/view/mixin/ConnectionsMixin.ts#L170-L175


The default was `true`, using the former "getValue" function in https://github.com/maxGraph/maxGraph/blob/c89ce4cea443c7950a7365c696225a4c48e7e8f6/packages/core/src/view/connection/GraphConnections.ts#L158-L159

Then, the default was removed, using CellStateStyle properties in https://github.com/maxGraph/maxGraph/blob/648e324cc06254c90694347dc216ac008aa63697/packages/core/src/view/connection/GraphConnections.ts#L178-L179


Finally, set to false . It uses the XOR operator ('||') instead of the Nullish coalescing operator ('??'), so it cannot be set to true, otherwise the value would have always been true. See https://github.com/maxGraph/maxGraph/blob/413796ad322ddfeb9228f9e4913a2d80b196fa0b/packages/core/src/view/mixins/ConnectionsMixin.ts#L267-L268

Do you think we should fix this in this PR or do we create another PR? This may impact several features/stories, so maybe it is safer to treat this in a dedicated PR.

Comment (redfish4ktc) [reply packages/core/src/view/mixin/ConnectionsMixin.ts:207]: I have changed the scope of #1028: it will include the change mentioned above

**Review by redfish4ktc — APPROVED** [review]
LGTM
Thanks for the analysis and the fix
