### PR TITLE
fix: TouchEvent is not available in Safari and Firefox Desktop

### LINKED ISSUE #76: `TouchEvent is not defined` error with Firefox Desktop / `Can't find variable: TouchEvent` error with Safari Desktop
**Environment**
- Firefox Desktop 95.0.1 and 96.0
- Ubuntu 20.04.3 LTS
- Node v16.13.1 npm 8.3.0
- commit 3494d0fb

The error is triggered when clicking on the Canvas or when selecting a shape or panning the graph as shown in the following video 👇

https://user-images.githubusercontent.com/27200110/150548100-938cd5b1-0480-4f0f-a131-b7c836ff61e9.mp4

```
Uncaught ReferenceError: TouchEvent is not defined
    consume InternalMouseEvent.ts:180
    consumeMouseEvent SelectionHandler.ts:544
    mouseUp SelectionHandler.ts:1462
    fireMouseEvent EventsMixin.ts:998
    installListeners CellRenderer.ts:788
```

Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1693172. It seems there is no issue when touch simulation is enabled (which is disabled by default on Desktop) or a touch device is detected.
Possible fix: https://stackoverflow.com/questions/27313488/touchevent-not-working-in-firefox-and-other-website-browser#32882849

### PR DESCRIPTION
**Pull request by zhangbiggs**
Apple M1 Pro
safari: Version 16.0 (17614.1.25.9.10, 17614)
Can't find variable: TouchEvent in safari

closes #76

### CODE REVIEW

**Comment by tbouffard** [comment]
Hi @zhangbihua and thanks for your contributions
Does the error you see look like something similar to the Firefox issue described in #76?
Could you provide the stack trace please?

Thanks in advance
[UPDATE] answer in https://github.com/maxGraph/maxGraph/issues/76#issuecomment-1283549618

**Review by tbouffard — APPROVED** [review]
✔️ Tested on Ubuntu 20 Desktop with Firefox 105.0 and the webkit version provided by [playwright](https://playwright.dev/) v1.27.0 (WebKit 16.0).
I didn't see errors in webkit prior the changes provided by this PR, so testing with webkit on Ubuntu is probably not relevant.

I will let this PR opened for a few days to let others test the changes with Safari and on mobile prior I merge.

File: packages/core/src/view/event/InternalMouseEvent.ts [hunk 1]
```diff
@@ -191,7 +191,7 @@ class InternalMouseEvent {
   consume(preventDefault?: boolean) {
     preventDefault = preventDefault
       ? preventDefault
-      : this.evt instanceof TouchEvent || isMouseEvent(this.evt);
+      : (isMouseEvent(this.evt) || this.evt instanceof TouchEvent);
```
Comment (mayorovad) [inline packages/core/src/view/event/InternalMouseEvent.ts]: I think it's more safe to add check for window.TouchEvent is not falsy, because in proposed approach if `isMouseEvent` will somehow return `false` Firefox/Safari will still fail.
 
```suggestion
      : (window.TouchEvent && this.evt instanceof TouchEvent) || isMouseEvent(this.evt);
```

Checked latest on Firefox/Chrome (desktop and touch emulations) and it works fine

Comment (tbouffard) [reply packages/core/src/view/event/InternalMouseEvent.ts]: Yes you are right, this is also what is proposed in the resources pointed in #76 
@zhangbihua what do you think about it?

**Comment by tbouffard** [comment]
@zhangbihua you recently push new commits that are not related to the fix for Safari and Firefox, could you revert them and tell us what you think about the @mayorovad 's proposal (https://github.com/maxGraph/maxGraph/pull/127#discussion_r1002674264)?

**Comment by zhangbiggs** [comment]
@tbouffard @mayorovad 
This is about fixing other bugs, not about this issue. My negligence has caused your workload. I'm really sorry. I will revert as soon as possible and establish new branch in my repo.


Regarding about the @mayorovad 's proposal, I guess mouseEvent is more generic than TouchEvent in different devices

```js
isMouseEvent(this.evt) || (window.TouchEvent && this.evt instanceof TouchEvent)
```
May be more effective

**Comment by tbouffard** [comment]
@zhangbihua thanks for removing extra commit
About your proposal, it's fine to me. The most important thing is to have the `window.TouchEvent` guard prior invoking `TouchEvent`

**Comment by tbouffard** [comment]
As a first implementation, I commited the proposal described in https://github.com/maxGraph/maxGraph/pull/127#pullrequestreview-1152270479. It is known as working and I wanted the fix to be integrated in the upcoming release.
Feel free to open a new Pull Request with another implementation if this one didn't fit well.
