### PR TITLE
fix(VertexHandle): add missing setPosition call in processEvent

### LINKED ISSUE #481: [BUG] Not possible to resize the inner rectangle in the `Handles` story
### To Reproduce

See https://maxgraph.github.io/maxGraph/demo/?path=/story/layouts-handles--default or run the story locally.

### Expected behavior
Be able to resize the inner rectangle as it was possible in mxGraph: https://jgraph.github.io/mxgraph/javascript/examples/handles.html

mxgraph_example_handles_resize_inner_OK

### Screenshots

maxgraph_story_handles_resize_inner_OK

### Environment
- Desktop
- OS and version: Ubuntu 20.04
- Browser and version: Firefox 126.0.1, Chrome 126.0.6478.126
- commit 50eb99b

### PR DESCRIPTION
**Pull request by HalilFocic**
Body of processEvent funciton inside VertexHandle was missing setPosition call that will properly update the values inside CellStyle This ensures the shape's internal lines are redrawn correctly during hnadle movements.

Before this change, dragging the custom handles did not update the shape's divider positions due to the missing setPosition call.

## PR Checklist

- [x] Addresses an existing open issue: Fixes #481 .
- [ ] You have discussed this issue with the maintainers of `maxGraph`, and you are assigned to the issue.
- [x] The scope of the PR is sufficiently narrow to be examined in a single session. A PR covering several issues must be split into separate PRs. Do not create a large PR, otherwise it cannot be reviewed and you will be asked to split it later or the PR will be closed.
- [x] I have added tests to prove my fix is effective or my feature works. This can be done in the form of automatic tests in `packages/core/_tests_` or a new or altered Storybook story in `packages/html/stories` (an existing story may also demonstrate the change).
- [x] I have provided screenshot/videos to demonstrate the change. If no releavant, explain why.
- [x] ~~I have added or edited necessary documentation,~~ or no docs changes are needed.
- [x] The PR title follows the ["Conventional Commits"](https://www.conventionalcommits.org/en/v1.0.0/) guidelines.

## Overview
Main issue was missing setPosition function call that was missing from processChange event. This line was  present inside mxGraph code, it probably got overlooked while migrating the code. Adding this line back caused the custom setPosition function written inside story to be triggered and position the label lines correctly.

After change:

https://github.com/user-attachments/assets/4063e9a7-5223-48e9-bbe4-a89014ab0cad

## Notes
:information_source: This change only reflects the inner rectangle issue,not rotating handle being misaligned, that was fixed in other PR.

## Summary by CodeRabbit

- **New Features**
	- Enhanced the Vertex Handle functionality to update its position based on mouse interactions and current state during event processing.

- **Bug Fixes**
	- Improved responsiveness of the Vertex Handle during user interactions.

### CODE REVIEW

File: packages/core/src/view/cell/VertexHandle.ts [hunk 1]
```diff
@@ -129,6 +129,7 @@ class VertexHandle implements CellHandle {
         alpha2
       )
     );
+    this.setPosition(this.state.getPaintBounds(), pt, me);
```
Comment (tbouffard) [inline packages/core/src/view/cell/VertexHandle.ts:132]: **praise:** Good catch. This seems to have been removed by mistake in a3102afa.
This line existed prior this commit and in the original mxGraph code

https://github.com/jgraph/mxgraph/blob/ff141aab158417bd866e2dfebd06c61d40773cd2/javascript/src/js/handler/mxHandle.js#L101-L105

**Review by tbouffard — APPROVED** [review]
LGTM, thanks for this contribution.
✔️ Tested locally
