### PR TITLE
fix(TooltipHandler): initialize the div when tooltip is shown

### LINKED ISSUE #200: Extra mxToolip elements created in the DOM
mxToolip DOM elements are created to render Tooltips. Currently in v0.2.0, one or several `mxTooltip` elements are created in the DOM even if Tooltips are not used.
I don't see any reason to create such elements and they were not created in the former mxGraph implementation.

This can be reproduce with Storybook stories, with the ts-example of this repository and examples of https://github.com/maxGraph/maxgraph-integration-examples

extra_mxTooltip_with_ts-example_2023-06-07
_DOM snapshot of the ts-example_

mxGraph examples showing there wasn't extra tooltip element
- https://jgraph.github.io/mxgraph/javascript/examples/shape.html
- https://jgraph.github.io/mxgraph/javascript/examples/markers.html

### First analysis

In mxGraph, the div was created only when calling the show method (if it didn’t previously exist):
- https://github.com/jgraph/mxgraph/blob/ff141aab158417bd866e2dfebd06c61d40773cd2/javascript/src/js/handler/mxTooltipHandler.js#L295-L309
- https://github.com/jgraph/mxgraph/blob/ff141aab158417bd866e2dfebd06c61d40773cd2/javascript/src/js/handler/mxTooltipHandler.js#L136

The div in maxGraph is currently created in the constructor: https://github.com/maxGraph/maxGraph/blob/v0.10.2/packages/core/src/view/handler/TooltipHandler.ts#L51-L55
This means that if the TooltipHandler plugin is declared at Graph initialization (default behavior), a tooltip div is always created even if it is never used.

The behavior should be restored (lazy loading) and the `init` method could be renamed into `ensureDivIsAvailable` if there is a naming clarification to do (this would reduce the compatibility with mxGraph).

### Notes for implementation

It should be feasible to add an automatic test that reproduce this behavior.

### PR DESCRIPTION
**Pull request by HalilFocic**
## PR Checklist

- [x] Addresses an existing open issue: fixes #200. If not, explain why (minor changes, etc.).
- [x] You have discussed this issue with the maintainers of `maxGraph`, and you are assigned to the issue.
- [x] The scope of the PR is sufficiently narrow to be examined in a single session. A PR covering several issues must be split into separate PRs. Do not create a large PR, otherwise it cannot be reviewed and you will be asked to split it later or the PR will be closed.
- [x] I have added tests to prove my fix is effective or my feature works. This can be done in the form of automatic tests in `packages/core/_tests_` or a new or altered Storybook story in `packages/html/stories` (an existing story may also demonstrate the change).
- [x] I have provided screenshot/videos to demonstrate the change. If no releavant, explain why.
- [x] ~~I have added or edited necessary documentation,~~ or no docs changes are needed.
- [x] The PR title follows the ["Conventional Commits"](https://www.conventionalcommits.org/en/v1.0.0/) guidelines.

## Overview

Current maxGraph Tooltip Handler code was not functioning same as mxGraph since we were creating the div inside constructor and not when ```show``` function was called like in maxGraph. This change fixes that by moving the logic from constructor to init function which is called if ```show``` function is called and div was null at that moment.

Tooltip functionality was tested on:
- Storybook examples mentioned in #200 and MenyStyle story that includes the tooltip.
- TS Example

## Notes

I did not provide any screenshots since it is pointless to screenshot the DOM that doesn't include mxTooltip.

## Summary by CodeRabbit

- **New Features**
	- Improved tooltip initialization and error handling for better user experience.
	- Expanded cleanup process for unreleased elements to include tooltips.

- **Bug Fixes**
	- Enhanced robustness by preventing errors related to tooltip visibility and state management.

### CODE REVIEW

File: packages/core/src/view/handler/TooltipHandler.ts [hunk 1]
```diff
@@ -314,13 +324,16 @@ class TooltipHandler implements GraphPlugin {
   onDestroy() {
     if (!this.destroyed) {
       this.graph.removeMouseListener(this);
-      InternalEvent.release(this.div);
+      if (this.div != null) {
+        InternalEvent.release(this.div);
+      }
 
-      if (this.div.parentNode) {
+      if (this.div != null && this.div.parentNode != null) {
```
Comment (tbouffard) [inline packages/core/src/view/handler/TooltipHandler.ts]: Why not this.div?.parentNode

File: packages/core/src/view/handler/TooltipHandler.ts [hunk 2]
```diff
@@ -314,13 +324,16 @@ class TooltipHandler implements GraphPlugin {
   onDestroy() {
     if (!this.destroyed) {
       this.graph.removeMouseListener(this);
-      InternalEvent.release(this.div);
+      if (this.div != null) {
```
Comment (tbouffard) [inline packages/core/src/view/handler/TooltipHandler.ts]: Why not if(this.div) ?

File: packages/core/src/view/handler/TooltipHandler.ts [hunk 3]
```diff
@@ -291,20 +299,22 @@ class TooltipHandler implements GraphPlugin {
   show(tip: HTMLElement | string | null, x: number, y: number) {
     if (!this.destroyed && tip && tip !== '') {
       const origin = getScrollOrigin();
-
-      this.div.style.zIndex = String(this.zIndex);
-      this.div.style.left = `${x + origin.x}px`;
-      this.div.style.top = `${y + TOOLTIP_VERTICAL_OFFSET + origin.y}px`;
+      if (this.div == null) {
```
Comment (tbouffard) [inline packages/core/src/view/handler/TooltipHandler.ts]: Why not if(!this.div)

File: packages/core/src/view/handler/TooltipHandler.ts [hunk 4]
```diff
@@ -280,8 +286,10 @@ class TooltipHandler implements GraphPlugin {
    * Hides the tooltip.
    */
   hideTooltip() {
-    this.div.style.visibility = 'hidden';
-    this.div.innerHTML = '';
+    if (this.div != null) {
```
Comment (tbouffard) [inline packages/core/src/view/handler/TooltipHandler.ts]: Why not if(this.div)

**Comment by tbouffard** [comment]
Hi this looks promising, I should be able to review this PR this week.

**Review by tbouffard — APPROVED** [review]
LGTM

Tested with ts-example and with Storybook by switching from to Boundary

- events: use tooltip
- boundary: not using the tooltip, no new tooltip, tooltip created by the Events story is cleaned by the  storybook script
