### PR TITLE
fix: popup menu story caused has more submenus open

### LINKED ISSUE #400: MenuStyle Story: the context menu (MaxPopupMenu) is always displayed
### Describe the bug
Context menu always show when change demo page：

image

### To Reproduce
1. Go to MenuStyle page and right click show Context menu
2. Click on other demo page, Context menu cannot hide auto
3. Back to MenuStyle page,right click show Context menu, two Context menus show

### PR DESCRIPTION
**Pull request by HalilFocic**
Added logic to remove mxPopupMenu,mxWidow and mxTooltip classes before each render. This should not impact the functionality since graph initialization inside story will add them afterwards.

## PR Checklist

- [x] Addresses an existing open issue: Partially fixes #400 
- [x] You have discussed this issue with the maintainers of `maxGraph`, and you are assigned to the issue.
- [x] The scope of the PR is sufficiently narrow to be examined in a single session. A PR covering several issues must be split into separate PRs. Do not create a large PR, otherwise it cannot be reviewed and you will be asked to split it later or the PR will be closed.
- [x] I have added tests to prove my fix is effective or my feature works. This can be done in the form of automatic tests in `packages/core/_tests_` or a new or altered Storybook story in `packages/html/stories` (an existing story may also demonstrate the change).
- [x] I have provided screenshot/videos to demonstrate the change. If no releavant, explain why.
- [x] I have added or edited necessary documentation
- [x] The PR title follows the ["Conventional Commits"](https://www.conventionalcommits.org/en/v1.0.0/) guidelines.

## Overview
Reason for this PR is issue #400. Basically Popups and Windows would stick when navigating from one story to another. Reason for this is lack of cleaning up the graph and properly destroying its resources while story is unmounting. 

I found no ways in storybook to call something on story unmount but since we instatiate graph when running each story, we can remove the classes before running any story by selecting all elements that have specific mx class and removing them from DOM.

This is how issue looked before:

https://github.com/user-attachments/assets/d4c9e547-1624-42fb-a60d-799ef4a04be6

After this change:

https://github.com/user-attachments/assets/ad8c7866-3d83-453b-8c75-bcdb620769d5

Also works properly with mxWindow inside Window story.

This probably fixes #400 

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved configuration reset process by removing specific UI elements during MaxGraph configuration reset.

### CODE REVIEW

File: packages/html/.storybook/preview.ts [hunk 1]
```diff
@@ -22,6 +22,10 @@ const resetMaxGraphConfigs = (): void => {
   resetHandleConfig();
   resetStyleDefaultsConfig();
   resetVertexHandlerConfig();
+  const classesToRemove = ['.mxPopupMenu', '.mxWindow', '.mxTooltip'];
```
Comment (tbouffard) [inline packages/html/.storybook/preview.ts:25]: **nitpick:** extra DOM elements using the mxTooltip class will be removed by #591
I will handle the change myself

**Review by tbouffard — APPROVED** [review]
LGTM
Tested with the following stories

For the popup menu feature:
- Events
- MenuStyle

For the MaxWindow feature:
- JsonData
- UserObject
