### PR TITLE
fix: correcly call 'isEdge' in CellEditorHandler

### LINKED ISSUE #228: getting error on edit of graph.
When I double-click on editable node, I get the following:

this.graph.model.isEdge is not a function
TypeError: this.graph.model.isEdge is not a function
    at CellEditorHandler.startEditing 

Am I doing something wrong?

### PR DESCRIPTION
**Pull request by TravisAdsitt**
**Summary**
Fix #228 

**Description for the changelog**
`isEdge` is not a model function but rather a function of the cell.

### CODE REVIEW

File: packages/core/src/view/handler/CellEditorHandler.ts [hunk 1]
```diff
@@ -799,7 +799,7 @@ class CellEditorHandler implements GraphPlugin {
       if (
         this.autoSize &&
         // @ts-ignore
```
Comment (tbouffard) [inline packages/core/src/view/handler/CellEditorHandler.ts]: **thought:** the ts-ignore directive should not be necessary if the code is correctly fixed.
I am checking this and will push a change directly if this is now correct.

Comment (tbouffard) [reply packages/core/src/view/handler/CellEditorHandler.ts]: Done in 5de66571

**Review by tbouffard — APPROVED** [review]
LGTM, thanks for your contribution @TravisAdsitt
